static:
  image: node:latest
  stage: build
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - public
  script:
    - npm install
    - npm build

image:
  image: docker:latest
  stage: build
  dependencies:
    - build:static
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY
    - docker build -t registry.gitlab.com/lecler-i/thomas.sh .
    - docker push registry.gitlab.com/lecler-i/thomas.sh

  only:
    - master
