stages:
  - build
  - release
  - deploy

build:static:
  image: node:latest
  stage: build
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - public/
  script:
    - npm install
    - npm run build

release:image:
  image: docker:latest
  stage: deploy
  variables:
    DOCKER_DRIVER: overlay
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker build -t registry.gitlab.com/lecler-i/thomas.sh .
    - docker push registry.gitlab.com/lecler-i/thomas.sh
  only:
    - master
