language: node_js

node_js:
  - "7"

script:
- yarn build

deploy:
  provider: pages
  skip_cleanup: true
  repo: 'lecler-i/lecler-i.github.io'
  target_branch: 'master'
  github_token: $GITHUB_TOKEN
  local_dir: 'public'
  on:
    branch: master
