language: node_js

node_js:
  - "7"

branches:
  only:
  - master

script:
- yarn build

deploy:
  provider: pages
  skip_cleanup: true
  repo: 'lecler-i/lecler-i.github.io'
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: 'public'
