# head
menu:
  カタログ/（目录）: /archives
  # sitemap: /sitemap.xml
  # other menus

rss: /atom.xml
favicon: /favicon.png

date_format: 'MMMM D, YYYY'

google_verification: false  # your token
google_analytics: false     # your id

disqus_shortname: false     # your disqus name

live2d: false    # true
hjid: false      # your hjid (hotjar)

start_year: 2016

reward_image: /img/wechat.png
